### ISSUE TITLE
Cannot detect 1D Code39

### ISSUE THREAD

**Issue by Enormity** [dsiddharth2/php-zxing#4]
I'm not sure if this is because it was not programmed to, or if there is an issue.  But it cannot detect a Code39 1D bar code.

**Comment by dsiddharth2** [comment]
Hi, I will test this and get back to you. Generally some times the Zxing library does not read the bar code. I have to check.

**Comment by dsiddharth2** [comment]
Hi,
I did try with Code39 again. It works for me.

I tried using the following,

![sample_code39_260x130](https://user-images.githubusercontent.com/6525909/39399239-00c166e2-4b38-11e8-82c9-6067d4a5639a.png)

**Comment by dsiddharth2** [comment]
Hi I tried working with different Bar Codes, it works fine. Some times because the bar code is not clearly visible, it will not read. For now I am marking the issue closed. Please re-open it if you feel the problem did not solve for you.

Also I think you should try the config,

`$config = array(
    'try_harder' => true
);`
